name: Build EE4ShinyItemBuilder

on:
  push:
    branches: [ "main" ] 
  workflow_dispatch:

jobs:
  EE4ShinyItemBuilder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      
      - name: Dependecies
        run: npm ci
        working-directory: ./vc
 
      - name: Build
        run: npm run build
        working-directory: ./vc
        
      - name: Push EE
        run: git push