name: Build EE4ShinyItemBuilder (1)

on:
  push:
    branches: [ "main" ]  

jobs:
  Node-Build-EE:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
 
      - name: Override NODE option
        run: echo "NODE_OPTIONS=--openssl-legacy-provider" >> $GITHUB_ENV
 
      - name: Dependecies
        run: npm install
        working-directory: ./vc
 
      - name: Build
        run: CI=false npm run build
        working-directory: ./vc
        
      - name: Push EE
        run: git push

      - name: Trigger "R-CMD-check"
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: ee-updated
        